# Default SwiftLint configuration for SchoolOrganizerNew

disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - identifier_name

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - toggle_bool

excluded:
  - Pods
  - SchoolOrganizerPlus.xcodeproj
  - SchoolReminderHelp WatchKit Extension

analyzer_rules:
  - unused_declaration
  - unused_import

force_unwrapping: warning
implicitly_unwrapped_optional: warning
